import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const roboto = Inter({ subsets: ['latin'], weight: ['100', '300', '400', '500', '600', '700', '900'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-white ${roboto.className}`}>{children}</body>
    </html>
  )
}
